### ISSUE TITLE
[JOSS REVIEW] - Add testing for the python versions you support

### ISSUE THREAD

**Issue by finsberg** [mad-lab-fau/imucal#20]
In your `pyproject.toml` you write that you support python `">=3.7.1,<3.11"`. 
However, in your [CI](https://github.com/mad-lab-fau/imucal/blob/master/.github/workflows/test-and-lint.yml) you only test for python3.7 and python3.8. 

I would recommend to either add python3.9 and python3.10 to your testing matrix or change the supported python versions in `pyproject.toml`

**Comment by finsberg** [comment]
I think it would also be worth testing for different operating systems.

**Comment by AKuederle** [comment]
I agree! I will update the pipeline to include the new python versions.

However, I will (if that is fine with you) not at testing on different operating systems. Given that we don't do anything that is known to cause operating system specific issues (expect a couple of path handling aspects, which we handle with `pathlib`), I don't think there is a lot of value in that. It will only tripple the amount of compute power we "waist" in the CI.

**Comment by AKuederle** [comment]
Ok that was a little bit more of a Rabit Hole than expected :D it seems like `hd5py` causes some issues with Python 3.10. However, as it is an optional dependency only needed for a small optional feature, I still consider 3.10 reported (I added a section in the README with details), but I removed 3.10 from the CI, as I would need to restructure the tests to exclude all tests that would fail without the optional dependency.

However, I will monitor the h5py release and retest in a couple of month (#21).

I will close the issue for now and track the issue for me in #21 so that I don't forget to check that again.
I hope that is sufficient for the context of this review. If you don't agree, feel free to reopen.

Thanks again for your input!

**Comment by AKuederle** [comment]
After some further testing, I think the issue with 3.10 is because of the specific version of h5py we were using. I will try to update it and I hope this will fix this issue properly.

**Comment by AKuederle** [comment]
Updating to a new h5py version indeed fixed the issues with Python 3.10. It required some small changes to the codebase. Hence, I created a new release.

With that Py 3.7-3.10 are all tested in the CI and the section in the README provides any further info about potential version/platform issues.

Now I will close this issue for good :) Feel free to reopen, if you think further changes are required.

For tracking: https://github.com/openjournals/joss-reviews/issues/4338
